GET http://localhost:3000/users

###
POST http://localhost:3000/add-user
Content-Type: application/json

{
    "name": "Catatan Baru Saya",
    "date": "2025-06-03",
    "note": "Ini adalah isi catatan pertama saya."
}

###
PUT http://localhost:3000/edit-user/1
Content-Type: application/json

{
    "name": "Catatan Diperbarui",
    "date": "2025-06-04",
    "note": "Isi catatan setelah diedit."
}

###
DELETE http://localhost:3000/delete-user/2
